spring: 
  profiles: 
    active: prod # 激活开发环境配置
---
spring: 
  profiles: dev # 开发环境
config:
  info: "master branch, config-dev, version = 1"
---
spring: 
  profiles: prod # 开发环境
config:
  info: "master branch, config-prod, version = 2"
